GET http://localhost:4000/ping
### Login
POST http://localhost:4000/auth/login
### Registrar
POST http://localhost:4000/auth/registrar
content-type: application/json

{
        "nomeCompleto": "Silva e Silva",
        "email": "silvaesilva@silva.com",
        "senha": "#Senha123",
        "dataCriacao": "2021-09-01T00:00:00.000Z",
        "token": "123456",
        "dataExpiracaoToken": "2021-09-01T00:00:00.000Z",
        "telefone": "123456",
        "imagemPerfil": "https://www.google.com.br"
}
### Login
# @name tokenAPI
POST http://localhost:4000/auth/login
content-type: application/json

{
        "email": "silvaesilva@silva.com",
        "senha": "#Senha123"
}

### Alterar Nome usuario 

#@authToken = {{tokenAPI.response.body}}
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywibm9tZUNvbXBsZXRvIjoiU2lsdmEgZSBTaWx2YSIsImVtYWlsIjoic2lsdmFlc2lsdmFAc2lsdmEuY29tIiwiZGF0YUNyaWFjYW8iOiIyMDIxLTA5LTAxVDAwOjAwOjAwLjAwMFoiLCJhdGl2byI6dHJ1ZSwidG9rZW4iOiIxMjM0NTYiLCJkYXRhRXhwaXJhY2FvVG9rZW4iOiIyMDIxLTA5LTAxVDAwOjAwOjAwLjAwMFoiLCJhdXRlbnRpY2FjYW9Eb2lzRmF0b3Jlc0F0aXZhIjpmYWxzZSwidGVsZWZvbmUiOiIxMjM0NTYiLCJpbWFnZW1QZXJmaWwiOiJodHRwczovL3d3dy5nb29nbGUuY29tLmJyIiwiaWF0IjoxNzM3NDIyMzcwLCJleHAiOjE3Mzg3MTgzNzB9._4UOEOAgsfmrNOn1-IGFx1PnmlQM5__niNIJ9NI8H4Q
PATCH http://localhost:4000/usuario/3/alterarNome
content-type: application/json
Authorization: Bearer {{authToken}}

{
        "nomeCompleto": "João da Silva"
}

###
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywibm9tZUNvbXBsZXRvIjoiU2lsdmEgZSBTaWx2YSIsImVtYWlsIjoic2lsdmFlc2lsdmFAc2lsdmEuY29tIiwiZGF0YUNyaWFjYW8iOiIyMDIxLTA5LTAxVDAwOjAwOjAwLjAwMFoiLCJhdGl2byI6dHJ1ZSwidG9rZW4iOiIxMjM0NTYiLCJkYXRhRXhwaXJhY2FvVG9rZW4iOiIyMDIxLTA5LTAxVDAwOjAwOjAwLjAwMFoiLCJhdXRlbnRpY2FjYW9Eb2lzRmF0b3Jlc0F0aXZhIjpmYWxzZSwidGVsZWZvbmUiOiIxMjM0NTYiLCJpbWFnZW1QZXJmaWwiOiJodHRwczovL3d3dy5nb29nbGUuY29tLmJyIiwiaWF0IjoxNzM3NDIyMzcwLCJleHAiOjE3Mzg3MTgzNzB9._4UOEOAgsfmrNOn1-IGFx1PnmlQM5__niNIJ9NI8H4Q
PATCH http://localhost:4000/usuario/3/alterarSenha
content-type: application/json
Authorization: Bearer {{authToken}}

{
        "senhaAtual": "#Senha123",
        "novaSenha": "#Senha1234",
        "confirmaNovaSenha": "#Senha1234"
}
